# <span style = "color : red"> <h2 style="text-align: center;"> Data Preparation and Experiments</h2> </span>
 <h3 style="text-align: center;"> Let's GO </h3>

In [2]:
# %pip install pathlib

In [3]:
import numpy as np
import pandas as pd
from pathlib import Path
import requests

In [4]:
data=[
    [2018,10,15,20],
    [2019,12,15,22],
    [2020,14,32,25],
    [2021,16,37,28],
    [2022,19,15,30]

]
simple_data=pd.DataFrame(data,columns=['year','col1','col2','col3'])

In [5]:
simple_data

year  col1  col2  col3
0  2018    10    15    20
1  2019    12    15    22
2  2020    14    32    25
3  2021    16    37    28
4  2022    19    15    30

In [6]:
data_dir=Path("data")

if data_dir.is_dir():
    print("path exist , skipping making.... ")

else:
    data_dir.mkdir(parents=True,
                   exist_ok=True)
    print("directory is made")

path exist , skipping making.... 


In [7]:
if Path(data_dir/'sample.csv').exists():
    print("file exist, skip creating.....")
else:
    simple_data.to_csv(data_dir/'sample.csv',index=False)
    

file exist, skip creating.....


In [8]:
sample_map=pd.DataFrame(
   { 'Location': ['Dhaka', 'Chittagong', 'Cox\'s Bazar', 'Sylhet', 'Sundarbans'],
    'Latitude': [23.8103, 22.3569, 21.4272, 24.8949, 21.9497],
    'Longitude': [90.4125, 91.7832, 92.0058, 91.8687, 89.1833]}
)

In [9]:
if Path(data_dir/'sample.csv').is_file():
    print("file exist, skip creating.....")
else:
    sample_map.to_csv(data_dir/'sample_map.csv',index=False)

file exist, skip creating.....


In [10]:
url="https://raw.githubusercontent.com/marcopeix/MachineLearningModelDeploymentwithStreamlit/master/12_dashboard_capstone/data/quarterly_canada_population.csv"

In [11]:
# creating file for capstone project canada populations

if (Path(data_dir/'c_people.csv')).exists():
    print("File exist already .......")
else:
    with open(data_dir/'c_people.csv',"wb") as f:
        request=requests.get("https://raw.githubusercontent.com/marcopeix/MachineLearningModelDeploymentwithStreamlit/master/12_dashboard_capstone/data/quarterly_canada_population.csv")
        f.write(request.content)
        print(f"File created ........ ")

File exist already .......


##  Transforming data for capstone project

In [12]:

df=pd.read_csv("../NOTEBOOK/data/c_people.csv")
df.sample(5)

Quarter    Canada  Newfoundland and Labrador  Prince Edward Island  \
123  Q2 2022  38644920                     523043                168358   
11   Q2 1994  28907448                     575670                133030   
85   Q4 2012  34836008                     527180                144520   
103  Q2 2017  36398013                     528544                148860   
96   Q3 2015  35702908                     528117                144546   

     Nova Scotia  New Brunswick   Quebec   Ontario  Manitoba  Saskatchewan  \
123      1007360         802862  8650692  14996014   1401967       1188338   
11        926109         749473  7184599  10776819   1120863       1008540   
85        943341         758673  8078388  13434943   1254178       1088959   
103       947384         764813  8272894  14006386   1328412       1146218   
96        936525         758842  8175272  13707118   1292227       1120967   

     Alberta  British Columbia  Yukon  Northwest Territories  Nunavut  
123  4502858           5273809  43518                  45698    40403  
11   2691443           3646632  29682                  40383    24205  
85   3900333           4590545  36425                  43681    34842  
103  4227969           4905210  39175                  44813    37335  
96   4144491           4776388  37690                  44237    36488

In [13]:
col_data=df['Quarter'][:]
# col_data=list(col_data)

year=list()
quarter=set()

for d in col_data:
    year.append(d[3:])
    quarter.add(d[:2])

quarter=list(quarter)

quarter,year[:4]

(['Q1', 'Q2', 'Q4', 'Q3'], ['1991', '1991', '1992', '1992'])

In [14]:
place=df.columns
place=place[1:]
place

Index(['Canada', 'Newfoundland and Labrador', 'Prince Edward Island',
       'Nova Scotia', 'New Brunswick', 'Quebec', 'Ontario', 'Manitoba',
       'Saskatchewan', 'Alberta', 'British Columbia', 'Yukon',
       'Northwest Territories', 'Nunavut'],
      dtype='object')

In [15]:
start_date='Q1 2012'
target="Quebec"

In [16]:
df.loc[df['Quarter']==start_date,target].item()

8029498

In [17]:
x=np.arange(2,100,2).reshape(-1,1)

y=x*3+2

In [18]:
x

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18],
       [20],
       [22],
       [24],
       [26],
       [28],
       [30],
       [32],
       [34],
       [36],
       [38],
       [40],
       [42],
       [44],
       [46],
       [48],
       [50],
       [52],
       [54],
       [56],
       [58],
       [60],
       [62],
       [64],
       [66],
       [68],
       [70],
       [72],
       [74],
       [76],
       [78],
       [80],
       [82],
       [84],
       [86],
       [88],
       [90],
       [92],
       [94],
       [96],
       [98]])

In [19]:
y

array([[  8],
       [ 14],
       [ 20],
       [ 26],
       [ 32],
       [ 38],
       [ 44],
       [ 50],
       [ 56],
       [ 62],
       [ 68],
       [ 74],
       [ 80],
       [ 86],
       [ 92],
       [ 98],
       [104],
       [110],
       [116],
       [122],
       [128],
       [134],
       [140],
       [146],
       [152],
       [158],
       [164],
       [170],
       [176],
       [182],
       [188],
       [194],
       [200],
       [206],
       [212],
       [218],
       [224],
       [230],
       [236],
       [242],
       [248],
       [254],
       [260],
       [266],
       [272],
       [278],
       [284],
       [290],
       [296]])

In [20]:
from sklearn.linear_model import LinearRegression

model=LinearRegression().fit(x,y)

In [21]:
x_pred=np.arange(1,13,2).reshape(-1,1)
model.predict(x_pred)

array([[ 5.],
       [11.],
       [17.],
       [23.],
       [29.],
       [35.]])

In [22]:
x_pred.reshape(6)

array([ 1,  3,  5,  7,  9, 11])

In [24]:
url="https://raw.githubusercontent.com/marcopeix/MachineLearningModelDeploymentwithStreamlit/master/19_caching_capstone2/data/mushrooms.csv"


if Path("data/mashroom.csv").is_file():
    print("file exist , skipping creation")

else:
    with open("data/mashroom.csv","wb") as file:
        request=requests.get(url)
        file.write(request.content)
        print("mashroom csv file created")


mashroom csv file created


In [25]:
mashroom_data_path="data/mashroom.csv"