# <span style = "color : red"> <h2 style="text-align: center;"> Data Preparation and Experiments</h2> </span>
 <h3 style="text-align: center;"> Let's GO </h3>

In [2]:
# %pip install pathlib

In [3]:
import numpy as np
import pandas as pd
from pathlib import Path
import requests

In [4]:
data=[
    [2018,10,15,20],
    [2019,12,15,22],
    [2020,14,32,25],
    [2021,16,37,28],
    [2022,19,15,30]

]
simple_data=pd.DataFrame(data,columns=['year','col1','col2','col3'])

In [5]:
simple_data

year  col1  col2  col3
0  2018    10    15    20
1  2019    12    15    22
2  2020    14    32    25
3  2021    16    37    28
4  2022    19    15    30

In [6]:
data_dir=Path("data")

if data_dir.is_dir():
    print("path exist , skipping making.... ")

else:
    data_dir.mkdir(parents=True,
                   exist_ok=True)
    print("directory is made")

path exist , skipping making.... 


In [7]:
if Path(data_dir/'sample.csv').exists():
    print("file exist, skip creating.....")
else:
    simple_data.to_csv(data_dir/'sample.csv',index=False)
    

file exist, skip creating.....


In [8]:
sample_map=pd.DataFrame(
   { 'Location': ['Dhaka', 'Chittagong', 'Cox\'s Bazar', 'Sylhet', 'Sundarbans'],
    'Latitude': [23.8103, 22.3569, 21.4272, 24.8949, 21.9497],
    'Longitude': [90.4125, 91.7832, 92.0058, 91.8687, 89.1833]}
)

In [9]:
if Path(data_dir/'sample.csv').is_file():
    print("file exist, skip creating.....")
else:
    sample_map.to_csv(data_dir/'sample_map.csv',index=False)

file exist, skip creating.....


In [10]:
url="https://raw.githubusercontent.com/marcopeix/MachineLearningModelDeploymentwithStreamlit/master/12_dashboard_capstone/data/quarterly_canada_population.csv"

In [11]:
# creating file for capstone project canada populations

if (Path(data_dir/'c_people.csv')).exists():
    print("File exist already .......")
else:
    with open(data_dir/'c_people.csv',"wb") as f:
        request=requests.get("https://raw.githubusercontent.com/marcopeix/MachineLearningModelDeploymentwithStreamlit/master/12_dashboard_capstone/data/quarterly_canada_population.csv")
        f.write(request.content)
        print(f"File created ........ ")

File exist already .......


##  Transforming data for capstone project

In [12]:

df=pd.read_csv("../NOTEBOOK/data/c_people.csv")
df.sample(5)

Quarter    Canada  Newfoundland and Labrador  Prince Edward Island  \
124  Q3 2022  38929902                     525972                170688   
40   Q3 2001  31020902                     522046                136665   
104  Q3 2017  36545236                     528249                150402   
48   Q3 2003  31644028                     518459                137227   
34   Q1 2000  30525872                     531774                136442   

     Nova Scotia  New Brunswick   Quebec   Ontario  Manitoba  Saskatchewan  \
124      1019725         812061  8695659  15109416   1409223       1194803   
40        932494         749820  7396456  11897534   1151454       1000239   
104       950108         766621  8302063  14070141   1334790       1150331   
48        937717         749441  7485753  12245039   1163596        996386   
34        934594         750786  7340269  11576994   1144428       1011141   

     Alberta  British Columbia  Yukon  Northwest Territories  Nunavut  
124  4543111           5319324  43789                  45605    40526  
40   3058108           4076950  30158                  40845    28133  
104  4241100           4929384  39610                  44891    37546  
48   3183065           4124482  30941                  42600    29322  
34   2974517           4026664  30495                  40623    27145

In [13]:
col_data=df['Quarter'][:]
# col_data=list(col_data)

year=list()
quarter=set()

for d in col_data:
    year.append(d[3:])
    quarter.add(d[:2])

quarter=list(quarter)

quarter,year[:4]

(['Q3', 'Q1', 'Q2', 'Q4'], ['1991', '1991', '1992', '1992'])

In [14]:
place=df.columns
place=place[1:]
place

Index(['Canada', 'Newfoundland and Labrador', 'Prince Edward Island',
       'Nova Scotia', 'New Brunswick', 'Quebec', 'Ontario', 'Manitoba',
       'Saskatchewan', 'Alberta', 'British Columbia', 'Yukon',
       'Northwest Territories', 'Nunavut'],
      dtype='object')

In [15]:
start_date='Q1 2012'
target="Quebec"

In [16]:
df.loc[df['Quarter']==start_date,target].item()

8029498

In [17]:
x=np.arange(2,100,2).reshape(-1,1)

y=x*3+2

In [18]:
x

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18],
       [20],
       [22],
       [24],
       [26],
       [28],
       [30],
       [32],
       [34],
       [36],
       [38],
       [40],
       [42],
       [44],
       [46],
       [48],
       [50],
       [52],
       [54],
       [56],
       [58],
       [60],
       [62],
       [64],
       [66],
       [68],
       [70],
       [72],
       [74],
       [76],
       [78],
       [80],
       [82],
       [84],
       [86],
       [88],
       [90],
       [92],
       [94],
       [96],
       [98]])

In [19]:
y

array([[  8],
       [ 14],
       [ 20],
       [ 26],
       [ 32],
       [ 38],
       [ 44],
       [ 50],
       [ 56],
       [ 62],
       [ 68],
       [ 74],
       [ 80],
       [ 86],
       [ 92],
       [ 98],
       [104],
       [110],
       [116],
       [122],
       [128],
       [134],
       [140],
       [146],
       [152],
       [158],
       [164],
       [170],
       [176],
       [182],
       [188],
       [194],
       [200],
       [206],
       [212],
       [218],
       [224],
       [230],
       [236],
       [242],
       [248],
       [254],
       [260],
       [266],
       [272],
       [278],
       [284],
       [290],
       [296]])

In [20]:
from sklearn.linear_model import LinearRegression

model=LinearRegression().fit(x,y)

In [21]:
x_pred=np.arange(1,13,2).reshape(-1,1)
model.predict(x_pred)

array([[ 5.],
       [11.],
       [17.],
       [23.],
       [29.],
       [35.]])

In [22]:
x_pred.reshape(6)

array([ 1,  3,  5,  7,  9, 11])

In [23]:
url="https://raw.githubusercontent.com/marcopeix/MachineLearningModelDeploymentwithStreamlit/master/19_caching_capstone2/data/mushrooms.csv"


if Path("data/mashroom.csv").is_file():
    print("file exist , skipping creation")

else:
    with open("data/mashroom.csv","wb") as file:
        request=requests.get(url)
        file.write(request.content)
        print("mashroom csv file created")


file exist , skipping creation


In [24]:
mashroom_data_path="data/mashroom.csv"

In [25]:
mf=pd.read_csv("data/mushrooms_final.csv")
mf.sample(5)

odor gill-size gill-color stalk-surface-above-ring  \
5614    s         n          b                        k   
1673    n         b          n                        s   
3395    c         n          g                        s   
5887    f         b          p                        s   
5761    y         n          b                        k   

     stalk-surface-below-ring stalk-color-above-ring stalk-color-below-ring  \
5614                        s                      w                      p   
1673                        f                      w                      w   
3395                        s                      w                      w   
5887                        f                      w                      w   
5761                        s                      w                      p   

     ring-type spore-print-color class  
5614         e                 w     p  
1673         e                 n     e  
3395         p                 k     p  
5887         p                 h     p  
5761         e                 w     p

In [26]:
f_columns=mf.columns
f_columns

Index(['odor', 'gill-size', 'gill-color', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'ring-type', 'spore-print-color', 'class'],
      dtype='object')

In [27]:
dc=dict()

In [28]:
for c in f_columns:
    #print(mf[c].unique())
    l=mf[c].unique()
    dc[c]=l

In [29]:
dc['odor']

array(['p', 'a', 'l', 'n', 'f', 'c', 'y', 's', 'm'], dtype=object)

In [30]:
cols=mf.columns
a,b,c=cols[:3]
a,b,c

('odor', 'gill-size', 'gill-color')

In [31]:
list(dc[a])

['p', 'a', 'l', 'n', 'f', 'c', 'y', 's', 'm']

### For Session State Management capstone project data saving 

In [32]:
url="https://raw.githubusercontent.com/marcopeix/MachineLearningModelDeploymentwithStreamlit/master/25_state_capstone/data/used_car_canada_clean.csv"
if Path("data/used_car_canada.csv").is_file():
    print("file exist , skipping creation")

else:
    with open("data/used_car_canada.csv","wb") as file:
        request=requests.get(url)
        file.write(request.content)
        print("car data canada csv file created")

car data canada csv file created


In [33]:
df=pd.read_csv("data/used_car_canada.csv")
df.sample(5)

price    miles    year           make                  model  \
89234   33929.0  37522.0  2017.0           jeep               Wrangler   
117823  53488.0  56430.0  2019.0      chevrolet                  Tahoe   
89876   37494.0  54377.0  2018.0           jeep  Wrangler JK Unlimited   
115802  14995.0  84566.0  2016.0          buick                 Verano   
48817   15000.0  81709.0  2014.0  mercedes_benz                C-Class   

       body_type vehicle_type drivetrain transmission fuel_type  engine_size  \
89234        suv        Truck        4WD       Manual  gasoline          3.6   
117823       suv        Truck        4WD    Automatic  gasoline          5.3   
89876        suv        Truck        4WD       Manual  gasoline          3.6   
115802     sedan          Car        FWD    Automatic  gasoline          2.4   
48817      sedan          Car        4WD    Automatic  gasoline          3.5   

       engine_block state  
89234             V    NS  
117823            V    BC  
89876             V    ON  
115802            I    NB  
48817             V    ON

In [37]:
df.shape

(269493, 13)

In [35]:
df.isnull().sum()

price           0
miles           0
year            0
make            0
model           0
body_type       0
vehicle_type    0
drivetrain      0
transmission    0
fuel_type       0
engine_size     0
engine_block    0
state           0
dtype: int64

In [36]:
df.isna().sum()

price           0
miles           0
year            0
make            0
model           0
body_type       0
vehicle_type    0
drivetrain      0
transmission    0
fuel_type       0
engine_size     0
engine_block    0
state           0
dtype: int64

In [41]:
cols=df.columns
cols

Index(['price', 'miles', 'year', 'make', 'model', 'body_type', 'vehicle_type',
       'drivetrain', 'transmission', 'fuel_type', 'engine_size',
       'engine_block', 'state'],
      dtype='object')

In [46]:
dc=dict()
def creating_required_data(mf):
    f_columns=mf.columns
    for c in f_columns:
        #print(mf[c].unique())
        l=mf[c].unique()
        dc[c]=l

In [58]:
mf=pd.read_csv("data/honda_toyota_ca.csv")
mn=int(min(mf['miles']))
mx=int(max(mf['miles']))
df= mf[['year','make','model','state']]

In [59]:
mn,mx

(0, 561500)

In [60]:
df

year    make    model state
0      2001.0  toyota    Prius    BC
1      2017.0  toyota    Prius    ON
2      2018.0  toyota    Prius    ON
3      2018.0  toyota    Prius    BC
4      2016.0  toyota    Prius    AB
...       ...     ...      ...   ...
39235  2016.0  toyota  Prius v    AB
39236  2012.0  toyota  Prius v    ON
39237  2014.0  toyota  Prius v    ON
39238  2014.0  toyota  Prius v    QC
39239  2017.0  toyota  Prius v    QC

[39240 rows x 4 columns]