# <span style = "color : red"> <h2 style="text-align: center;"> Data Preparation and Experiments</h2> </span>
 <h3 style="text-align: center;"> Let's GO </h3>

In [1]:
# %pip install pathlib

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
import requests

In [3]:
data=[
    [2018,10,15,20],
    [2019,12,15,22],
    [2020,14,32,25],
    [2021,16,37,28],
    [2022,19,15,30]

]
simple_data=pd.DataFrame(data,columns=['year','col1','col2','col3'])

In [4]:
simple_data

year  col1  col2  col3
0  2018    10    15    20
1  2019    12    15    22
2  2020    14    32    25
3  2021    16    37    28
4  2022    19    15    30

In [5]:
data_dir=Path("data")

if data_dir.is_dir():
    print("path exist , skipping making.... ")

else:
    data_dir.mkdir(parents=True,
                   exist_ok=True)
    print("directory is made")

path exist , skipping making.... 


In [6]:
if Path(data_dir/'sample.csv').exists():
    print("file exist, skip creating.....")
else:
    simple_data.to_csv(data_dir/'sample.csv',index=False)
    

file exist, skip creating.....


In [7]:
sample_map=pd.DataFrame(
   { 'Location': ['Dhaka', 'Chittagong', 'Cox\'s Bazar', 'Sylhet', 'Sundarbans'],
    'Latitude': [23.8103, 22.3569, 21.4272, 24.8949, 21.9497],
    'Longitude': [90.4125, 91.7832, 92.0058, 91.8687, 89.1833]}
)

In [8]:
if Path(data_dir/'sample.csv').is_file():
    print("file exist, skip creating.....")
else:
    sample_map.to_csv(data_dir/'sample_map.csv',index=False)

file exist, skip creating.....


In [9]:
url="https://raw.githubusercontent.com/marcopeix/MachineLearningModelDeploymentwithStreamlit/master/12_dashboard_capstone/data/quarterly_canada_population.csv"

In [10]:
# creating file 

if (Path(data_dir/'c_people.csv')).exists():
    print("File exist already .......")
else:
    with open(data_dir/'c_people.csv',"wb") as f:
        request=requests.get("https://raw.githubusercontent.com/marcopeix/MachineLearningModelDeploymentwithStreamlit/master/12_dashboard_capstone/data/quarterly_canada_population.csv")
        f.write(request.content)
        print(f"File created ........ ")

File exist already .......


##  Transforming data for capstone project

In [11]:

df=pd.read_csv("../NOTEBOOK/data/c_people.csv")
df.sample(5)

Quarter    Canada  Newfoundland and Labrador  Prince Edward Island  \
61   Q4 2006  32680712                     510329                137898   
75   Q2 2010  33889236                     521204                140990   
104  Q3 2017  36545236                     528249                150402   
62   Q1 2007  32717701                     510335                137778   
116  Q3 2020  38007166                     521359                161305   

     Nova Scotia  New Brunswick   Quebec   Ontario  Manitoba  Saskatchewan  \
61        937046         744975  7653092  12700994   1183981        993361   
75        940919         752021  7903339  13088106   1216610       1046799   
104       950108         766621  8302063  14070141   1334790       1150331   
62        936203         744853  7661583  12702838   1184503        995174   
116       981691         782996  8576595  14726022   1379888       1178467   

     Alberta  British Columbia  Yukon  Northwest Territories  Nunavut  
61   3453944           4258655  32361                  43197    30879  
75   3714974           4453744  34241                  43152    33137  
104  4241100           4929384  39610                  44891    37546  
62   3472771           4265321  32315                  43074    30953  
116  4416682           5155495  42163                  45346    39157

In [12]:
col_data=df['Quarter'][:]
# col_data=list(col_data)

year=list()
quarter=set()

for d in col_data:
    year.append(d[3:])
    quarter.add(d[:2])

quarter=list(quarter)

quarter,year[:4]

(['Q3', 'Q4', 'Q2', 'Q1'], ['1991', '1991', '1992', '1992'])

In [13]:
place=df.columns
place=place[1:]
place

Index(['Canada', 'Newfoundland and Labrador', 'Prince Edward Island',
       'Nova Scotia', 'New Brunswick', 'Quebec', 'Ontario', 'Manitoba',
       'Saskatchewan', 'Alberta', 'British Columbia', 'Yukon',
       'Northwest Territories', 'Nunavut'],
      dtype='object')

In [14]:
start_date='Q1 2012'
target="Quebec"

In [15]:
df.loc[df['Quarter']==start_date,target].item()

8029498

In [56]:
x=np.arange(2,100,2).reshape(-1,1)

y=x*3+2

In [57]:
x

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18],
       [20],
       [22],
       [24],
       [26],
       [28],
       [30],
       [32],
       [34],
       [36],
       [38],
       [40],
       [42],
       [44],
       [46],
       [48],
       [50],
       [52],
       [54],
       [56],
       [58],
       [60],
       [62],
       [64],
       [66],
       [68],
       [70],
       [72],
       [74],
       [76],
       [78],
       [80],
       [82],
       [84],
       [86],
       [88],
       [90],
       [92],
       [94],
       [96],
       [98]])

In [58]:
y

array([[  8],
       [ 14],
       [ 20],
       [ 26],
       [ 32],
       [ 38],
       [ 44],
       [ 50],
       [ 56],
       [ 62],
       [ 68],
       [ 74],
       [ 80],
       [ 86],
       [ 92],
       [ 98],
       [104],
       [110],
       [116],
       [122],
       [128],
       [134],
       [140],
       [146],
       [152],
       [158],
       [164],
       [170],
       [176],
       [182],
       [188],
       [194],
       [200],
       [206],
       [212],
       [218],
       [224],
       [230],
       [236],
       [242],
       [248],
       [254],
       [260],
       [266],
       [272],
       [278],
       [284],
       [290],
       [296]])

In [59]:
from sklearn.linear_model import LinearRegression

model=LinearRegression().fit(x,y)

In [64]:
x_pred=np.arange(1,13,2).reshape(-1,1)
model.predict(x_pred)

array([[ 5., 11., 17., 23., 29., 35.]])

In [67]:
x_pred.reshape(6)

array([ 1,  3,  5,  7,  9, 11])